version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: school_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    
  app:
    build: .
    container_name: nextjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    entrypoint: ["sh", "-c", "npx prisma migrate deploy && npm run start"]

volumes:
  postgres_data: