version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: school_db
    restart: always
    environment:
      POSTGRES_USER: bachir
      POSTGRES_PASSWORD: bachirou77
      POSTGRES_DB: master_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U bachir -d master_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: nextjs_app--dev
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: "environment"
      DATABASE_URL: "postgresql://bachir:bachirou77@postgres:5432/master_db"
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
      NEXT_PUBLIC_CLOUDINARY_API_KEY: ${NEXT_PUBLIC_CLOUDINARY_API_KEY}

volumes:
  postgres_data: