version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: bachirse
      POSTGRES_PASSWORD: bachirou77
      POSTGRES_DB: school
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    container_name: nextjs-app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://bachirse:bachirou77@localhost:5432/school
    command: ["npm", "start"]

volumes:
  postgres_data:
