version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: bachirse
      POSTGRES_PASSWORD: bachirou77
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - school_dashboard_postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  school_dashboard_postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /Volumes/postgres_data
      o: bind

networks:
  my_network:
    driver: bridge
