name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (optional, useful for cross-platform builds, you can skip if not needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t school-app:v1.0.0 .

      # Step 4: SSH into VPS and deploy the app
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          run: |
            # Stop and remove any old container (if it exists)
            docker stop nextjs-app || true
            docker rm nextjs-app || true

            # Pull the latest image (in case you use Docker Hub in future) or build directly on VPS
            # docker pull school-app:v1.0.0 || true  # Uncomment if you are using a registry

            # Run the container with the built image
            docker run -d --name nextjs-app -p 80:3000 school-app:v1.0.0
